import random
from datetime import datetime

def generate_quiz_html():
    categories = [
        ("1) Single digit number addition", 1, 2),
        ("2) Single digit addition of 5", 1, 5),
        ("3) Double digit addition", 2, 2),
        ("4) Double digit addition of 5", 2, 5),
        ("5) 3-digit + 2-digit addition", "3+2", 2),
        ("6) 3-digit addition", 3, 2)
    ]

    quiz_html = ""
    answer_html = ""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    for label, digit_type, count in categories:
        quiz_html += f"<h3>{label}</h3><ol>"
        answer_html += f"<div><strong>{label}:</strong><br>"
        
        current_answers = []
        for _ in range(5):
            if digit_type == "3+2":
                num1 = random.randint(100, 999)
                num2 = random.randint(10, 99)
                numbers = [num1, num2]
            else:
                start = 10**(digit_type - 1) if digit_type > 1 else 1
                end = (10**digit_type) - 1
                numbers = [random.randint(start, end) for _ in range(count)]

            question_text = " + ".join(map(str, numbers))
            answer = sum(numbers)
            
            quiz_html += f"<li>{question_text} = ________</li>"
            current_answers.append(str(answer))
        
        quiz_html += "</ol>"
        answer_html += " | ".join(current_answers) + "</div><br>"

    # Final HTML Construction with CSS styling
    html_content = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Daily Math Quiz</title>
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; max-width: 800px; margin: 40px auto; padding: 20px; color: #333; }}
            h1 {{ border-bottom: 2px solid #4CAF50; color: #2E7D32; }}
            h3 {{ background: #f4f4f4; padding: 8px; border-radius: 4px; color: #555; }}
            .footer {{ margin-top: 50px; font-size: 0.8em; color: #888; border-top: 1px solid #ddd; padding-top: 10px; }}
            .answers {{ background: #fffbe6; padding: 20px; border: 1px dashed #d4a017; border-radius: 8px; margin-top: 40px; }}
            li {{ margin-bottom: 10px; font-weight: bold; font-size: 1.1em; }}
        </style>
    </head>
    <body>
        <h1>🧮 Daily Math Practice</h1>
        <p>Generated on: {timestamp}</p>
        
        <div class="quiz-section">
            {quiz_html}
        </div>

        <div class="answers">
            <h2>🔑 Answer Key</h2>
            {answer_html}
        </div>

        <div class="footer">
            Generated by Math Quiz Python Script.
        </div>
    </body>
    </html>
    """

    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)
    
    print("✅ Successfully generated index.html!")

if __name__ == "__main__":
    generate_quiz_html()
